package com.kamel.projects.domain.model

enum class Currency(val code: String, val displayName: String, val symbol: String) {
    USD("USD", "US Dollar", "$"),
    EUR("EUR", "Euro", "€"),
    TND("TND", "Tunisian Dinar", "د.ت"),
    CNY("CNY", "Chinese Yuan", "¥"),
    CAD("CAD", "Canadian Dollar", "C$"),
    NZD("NZD", "New Zealand Dollar", "NZ$"),
    GBP("GBP", "British Pound", "£"),
    JPY("JPY", "Japanese Yen", "¥"),
    AUD("AUD", "Australian Dollar", "A$"),
    CHF("CHF", "Swiss Franc", "CHF"),
    SEK("SEK", "Swedish Krona", "kr"),
    NOK("NOK", "Norwegian Krone", "kr"),
    DKK("DKK", "Danish Krone", "kr"),
    PLN("PLN", "Polish Zloty", "zł"),
    CZK("CZK", "Czech Koruna", "Kč"),
    HUF("HUF", "Hungarian Forint", "Ft"),
    RUB("RUB", "Russian Ruble", "₽"),
    INR("INR", "Indian Rupee", "₹"),
    KRW("KRW", "South Korean Won", "₩"),
    SGD("SGD", "Singapore Dollar", "S$"),
    HKD("HKD", "Hong Kong Dollar", "HK$"),
    THB("THB", "Thai Baht", "฿"),
    MYR("MYR", "Malaysian Ringgit", "RM"),
    PHP("PHP", "Philippine Peso", "₱"),
    IDR("IDR", "Indonesian Rupiah", "Rp"),
    VND("VND", "Vietnamese Dong", "₫"),
    BRL("BRL", "Brazilian Real", "R$"),
    MXN("MXN", "Mexican Peso", "$"),
    ARS("ARS", "Argentine Peso", "$"),
    CLP("CLP", "Chilean Peso", "$"),
    COP("COP", "Colombian Peso", "$"),
    PEN("PEN", "Peruvian Sol", "S/"),
    ZAR("ZAR", "South African Rand", "R"),
    EGP("EGP", "Egyptian Pound", "£"),
    MAD("MAD", "Moroccan Dirham", "د.م."),
    NGN("NGN", "Nigerian Naira", "₦"),
    KES("KES", "Kenyan Shilling", "KSh"),
    GHS("GHS", "Ghanaian Cedi", "₵"),
    TRY("TRY", "Turkish Lira", "₺"),
    ILS("ILS", "Israeli Shekel", "₪"),
    SAR("SAR", "Saudi Riyal", "﷼"),
    AED("AED", "UAE Dirham", "د.إ"),
    QAR("QAR", "Qatari Riyal", "﷼"),
    KWD("KWD", "Kuwaiti Dinar", "د.ك"),
    BHD("BHD", "Bahraini Dinar", ".د.ب"),
    OMR("OMR", "Omani Rial", "﷼"),
    JOD("JOD", "Jordanian Dinar", "د.ا"),
    LBP("LBP", "Lebanese Pound", "ل.ل"),
    SYP("SYP", "Syrian Pound", "£"),
    IQD("IQD", "Iraqi Dinar", "ع.د"),
    IRR("IRR", "Iranian Rial", "﷼"),
    AFN("AFN", "Afghan Afghani", "؋"),
    PKR("PKR", "Pakistani Rupee", "₨"),
    BDT("BDT", "Bangladeshi Taka", "৳"),
    LKR("LKR", "Sri Lankan Rupee", "₨"),
    NPR("NPR", "Nepalese Rupee", "₨"),
    BTN("BTN", "Bhutanese Ngultrum", "Nu."),
    MMK("MMK", "Myanmar Kyat", "K"),
    KHR("KHR", "Cambodian Riel", "៛"),
    LAK("LAK", "Laotian Kip", "₭"),
    MNT("MNT", "Mongolian Tugrik", "₮"),
    KZT("KZT", "Kazakhstani Tenge", "₸"),
    UZS("UZS", "Uzbekistani Som", "лв"),
    KGS("KGS", "Kyrgystani Som", "лв"),
    TJS("TJS", "Tajikistani Somoni", "SM"),
    TMT("TMT", "Turkmenistani Manat", "T"),
    AZN("AZN", "Azerbaijani Manat", "₼"),
    GEL("GEL", "Georgian Lari", "₾"),
    AMD("AMD", "Armenian Dram", "֏"),
    BYN("BYN", "Belarusian Ruble", "Br"),
    UAH("UAH", "Ukrainian Hryvnia", "₴"),
    MDL("MDL", "Moldovan Leu", "L"),
    RON("RON", "Romanian Leu", "lei"),
    BGN("BGN", "Bulgarian Lev", "лв"),
    HRK("HRK", "Croatian Kuna", "kn"),
    RSD("RSD", "Serbian Dinar", "Дин."),
    BAM("BAM", "Bosnia-Herzegovina Convertible Mark", "KM"),
    MKD("MKD", "Macedonian Denar", "ден"),
    ALL("ALL", "Albanian Lek", "Lek"),
    EUR_LEGACY("EUR", "Euro (Legacy)", "€")
}
